django/PRACTICE/PRACTICE/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('univ/', include('crud.urls')),  # school에서 univ로 바뀌어도 작동하게끔 app_name:name 형식을 사용한다.
    path('accounts/', include('accounts.urls'))   # accounts
]

django/PRACTICE/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup', views.signup, name='signup'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
]

django/PRACTICE/crud/urls.py
from django.contrib import admin
from django.urls import path
from . import views

# URL을 변수로 사용 (app_name:name)
app_name = 'crud'

urlpatterns = [
    # path('new/', views.new, name='new'),   # crud:new
    path('create/', views.create, name='create'),
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    # path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/reply/create/', views.reply_create, name='reply_create'),
    path('<int:pk>/reply/<int:reply_pk>/delete/', views.reply_delete, name='reply_delete'),
]

django/PRACTICE/accounts/models.py
from django.db import models

# Create your models here.

django/PRACTICE/crud/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth import get_user_model

# User = get_user_model()
AUTH_USER_MODEL = 'User'

# Create your models here.
class Student(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    age = models.IntegerField()
    major = models.CharField(max_length=10)
    description = models.TextField()
    # Timestamp => 생성시간/수정시간
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True)
    
class Reply(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    rank = models.IntegerField()
    

django/PRACTICE/crud/forms.py
from django import forms
from .models import Student, Reply

class StudentForm(forms.ModelForm):
    # 상수(값이 초기화/할당 이후 절대 변하면 안된다는 뜻)
    CHOICES = [
        ('SOC', '사회학'),
        ('POL', '정치외교학'),
        ('PSY', '심리학'),
        ('CSE', '컴퓨터공학')
    ]
    
    name = forms.CharField(min_length=1, max_length=10)
    age = forms.IntegerField(min_value=10, max_value=200)
    major = forms.ChoiceField(
        widget=forms.Select(),
        choices=CHOICES
    )
    description = forms.CharField(
        widget=forms.Textarea(),
        min_length=5
    )
    
    class Meta:
        model = Student
        exclude = ('user',)

class ReplyForm(forms.ModelForm):
    CHOICES = [
        (1, '★'),
        (2, '★★'),
        (3, '★★★'),
        (4, '★★★★'),
        (5, '★★★★★'),
    ]
    
    rank = forms.ChoiceField(
        widget=forms.Select(),
        choices=CHOICES
    )
    class Meta:
        model = Reply
        fields = ('content', 'rank',)

# PRACTICE > crud app 에서 ModelForm 사용하기
 # crud/forms.py 생성
# forms.py 에 StudentForm 이라는 모델폼 생성
# 모델은 Student
# 필드는 모든 필드
# new.html 과 edit.html 에서 <form> 의 제출 방식(method) 를 모두 POST 로 교체
# 토큰 잊지 않기
# new.html 과 edit.html 에서 <input> 요소들 모두 form 에서 출력하도록 교체
# create 와 update 에서 사용자 입력을 검증
# 유효할 경우에만 저장.
# 유효하지 않을 경우, 에러메세지와 함꼐 html 다시 렌더

django/PRACTICE/crud/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Student, Reply
from .forms import StudentForm, ReplyForm

from django.views.decorators.http import require_safe, require_http_methods, require_POST
from django.contrib.auth.decorators import login_required
# Create your views here.
# def new(request):
    # form = StudentForm()
    # return render(request, 'crud/new.html',{
        # 'form': form
    # })

@login_required
@require_http_methods(['GET', 'POST'])
def create(request):
    # form = StudentForm(data=request.POST)
    if request.method == 'GET':
        form = StudentForm()
    
    elif request.method == 'POST':
        form = StudentForm(data=request.POST)
        
        if form.is_valid():
            student = form.save(commit=False)
            student.user = request.user
            student.save()
            return redirect('crud:detail', student.pk)

    return render(request, 'crud/form.html', {
        'form': form
    })

@require_safe
def index(request):
    students = Student.objects.all()
    return render(request, 'crud/index.html', {
        'students': students,
    })

@require_safe
def detail(request, pk):
    # student = Student.objects.get(pk=pk)
    student = get_object_or_404(Student, pk=pk)
    form_reply = ReplyForm()
    return render(request, 'crud/detail.html', {
        'student': student,
        'form_reply': form_reply,
    })

# def edit(request, pk):
    # student = Student.objects.get(pk=pk)
    # form = StudentForm(instance=student)
    # return render(request, 'crud/edit.html', {
        # 'student': student,
        # 'form': form,
    # })
@login_required
@require_http_methods(['GET', 'POST'])
def update(request, pk):
    # student = Student.objects.get(pk=pk)
    student = get_object_or_404(Student, pk=pk)
    
    if request.method == 'GET':
        form = StudentForm(instance=student)
        
    elif request.method == 'POST':
        form = StudentForm(data=request.POST, instance=student)
    
        if form.is_valid():
            student = form.save()
            return redirect('crud:detail', student.pk)

    return render(request, 'crud/form.html', {
        'form': form,
    })
@login_required
@require_POST
def delete(request, pk):
    # student = Student.objects.get(pk=pk)
    student = get_object_or_404(Student, pk=pk)
    student.delete()
    # '/school/'
    return redirect('crud:index')


# comments 부분
@login_required
@require_POST
def reply_create(request, pk):
    student = get_object_or_404(Student, pk=pk)
    form_reply = ReplyForm(data = request.POST)
    if form_reply.is_valid():
        reply = form_reply.save(commit=False)
        reply.student = student
        reply.user = request.user
        reply.save()
    return redirect('crud:detail', student.pk)
    

@login_required
@require_POST
def reply_delete(request, pk, reply_pk):
    student = get_object_or_404(Student, pk=pk)
    reply = get_object_or_404(Reply, pk=reply_pk)
   
    
    if reply.user == request.user:
        reply.delete()
    
    return redirect('crud:detail', student.pk)

django/PRACTICE/crud/templates/crud/detail.html
{% extends "base.html" %}

{% block content %}

<h1>{{ student.name }}</h1>
<h2>작성자: {{ student.user }}</h2>

<p>나이: {{ student.age }}</p>
<p>전공: {{ student.major }}</p>
<p>비고: {{ student.description }}</p>

{% if request.user == student.user %}
<div>
    <!-- "/school/{{ student.pk }}/edit" -->
    <a href="{% url "crud:update" student.pk %}">
        <button>학생 정보 수정하기</button>
    </a>
</div>
<div>
    <!-- "/school/{{ student.pk }}/delete" -->
    <form action="{% url "crud:delete" student.pk %}" method='POST'>
        {% csrf_token %}
        <button onclick="alert('{{ student.name }} 학생 정보를 삭제하시겠습니까?')">학생 정보 삭제하기</button>
    </form>
</div>
{% endif %}

<hr>

{% include "crud/detail_reply.html" %}

{% endblock content %}

django/PRACTICE/crud/templates/crud/detail_reply.html
{% if request.user.is_authenticated %}
<form action="{% url "crud:reply_create" student.pk %}" method="POST">
  {% csrf_token %}
  {{ form_reply.as_p }}
  <button>댓글작성</button>
</form>
{% endif %}

<div>
  <ul>
  {% for reply in student.reply_set.all %}
    <li>
      {{ reply.user }}  {{ reply.content }}  {{ reply.rank }}

      {% if request.user == reply.user %}
      <form action="{% url "crud:reply_delete" student.pk reply.pk %}" method="POST" style="display: inline-block;">
        {% csrf_token %}
        <button onclick="return confirm('댓글 삭제?')">삭제</button>
      </form>
      {% endif %}
    </li>
  {% endfor %}
  </ul>
</div>

django/PRACTICE/crud/templates/crud/edit.html
{% extends "base.html" %}

{% block content %}
<!-- "/school/{{ student.pk }}/update/" -->
<form action="{% url "crud:update" student. pk %}" method="POST">
    {% csrf_token %}

    <table>
        {{ form.as_table }}
    </table>
    

    <div>
        <button onclick="alert('내용을 수정하시겠습니까?')">수정하기</button>
    </div>
</form>

{% endblock content %}

django/PRACTICE/crud/templates/crud/form.html
{% extends 'base.html' %}

{% block content %}
<form method="POST">
    {% csrf_token %}

    <table>
        {{ form.as_table }}
    </table>
    

    <div>
        <button>제출</button>
    </div>
</form>


{% endblock content %}

django/PRACTICE/crud/templates/crud/index.html
{% extends "base.html" %}

{% block content %}

<h2>전체 학생 목록</h2>

<ul>
    {% for student in students %}
    <li>
        <!-- '/school/{{ student.pk }}/' -->
        <a href="{% url "crud:detail" student.pk %}">
            {{ student.name }}
        </a>작성자: {{ student.user}}
    </li>
    {% endfor %}
</ul>

{% endblock content %}

django/PRACTICE/crud/templates/crud/new.html
{% extends "base.html" %}

{% block content %}
<!-- "/school/create/" -->
<form action="{% url "crud:create" %}" method="POST">
    {% csrf_token %}

    <table>
        {{ form.as_table }}
    </table>
    

    <div>
        <button>제출</button>
    </div>
</form>

{% endblock content %}